version: 2
updates:
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"
      day: "saturday"
    rebase-strategy: "auto"
    commit-message:
      include: scope
      prefix: ":arrow_up:"
    reviewers:
      - "BlueGlassBlock"
