name: Update Changelog

inputs:
  tag-name:
    description: Tag Name
    required: true

runs:
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.11

    - run: |
        echo "TAG_NAME=${{ inputs.tag-name }}" >> $GITHUB_ENV

    - name: Write and Push
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: dev
        token: ${{ secrets.GH_TOKEN }}
      run: |
        python ./extract-release-notes.py ${{ env.TAG_NAME }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff-index --quiet HEAD || git commit -m ":memo: update changelog"
        git push
        git checkout origin/master -b master
        git merge dev --ff-only
        git push --set-upstream origin master
      with:
        ref: master
        token: ${{ secrets.GH_TOKEN }}
